### ISSUE TITLE
[Un]MarshalBinary routines for peer.ID?

### ISSUE THREAD

**Issue by ktnyt** [libp2p/go-libp2p-peer#21]
I was unsure if there was any reasoning behind supporting so many Encoding/Decoding routines and yet not having the interfaces for MarshalBinary/UnmarshalBinary. I do acknowledge the fact that the existing interfaces do suffice most needs but I was just wondering if there could be room for these methods.

**Comment by hsanjuan** [comment]
I have added those in #44
