### ISSUE TITLE
Feature request: add a Set type (like cid.Set)

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-libp2p-peer#31]
It would be useful for me that we could have sets of peer  IDs like we can have sets of Cids

Basically doing: https://github.com/ipfs/go-cid/blob/master/set.go here.

@lanzafame do you want to take care of this?

**Comment by lanzafame** [comment]
@hsanjuan you mean like [`peerset`](https://github.com/libp2p/go-libp2p-peer/blob/master/peerset/peerset.go)? It is not the exact same set of methods but I can extend it if peerset doesn't have sufficient functionality for what you are trying to do?

**Comment by hsanjuan** [comment]
IM SO BLIND!
