### ISSUE TITLE
separate peerstore from peer package

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-peer#5]
These two don't really need to be in the same package. Separating them out makes updating the peerstore code much easier.

**Comment by shazow** [comment]
Also please clarify the distinction between these two packages. :) Seems they share 90% of the same code, I assume that's temporary.

**Comment by whyrusleeping** [comment]
It would appear that i forgot to push some code... Thanks for pointing this out

**Comment by whyrusleeping** [comment]
dun dun doneeeee
